name: Build Entlehnliste
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          pwd
      - run: echo "ðŸ This job's status is ${{ job.status }}."

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: show java version
        run: java -version

  docs:
    name: documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Hello
        run: |
          mkdir -p dist
          echo "hello, world\n" > dist/demo.txt
          pwd
          ls -l
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: dist
  
  deploy:
    permissions: write-all
    needs:
      - build
      - docs

    runs-on: ubuntu-22.04
    steps:
      - name: Download our text file
        uses: actions/download-artifact@v3
        with:
          name: hello

      - run: |
          pwd
          ls -l
          echo demo.txt
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            file: demo.txt
            tags: false
            overwrite: true
            update_latest_release: true
            verbose: true
      - run: echo "done"
